import Sidebar from './components/Sidebar'
import Chatbot from './components/Chatbot'

export default function App() {
  return (
    <div className="app">
      <Sidebar />
      <main className="main">
        <div className="main__header">
          <h1>my-projectttt</h1>
          <p>Generated by Project Composer</p>
        </div>
        <div className="main__content">
          <Chatbot />
        </div>
      </main>
    </div>
  )
}
